- name: Install Screenly OSE Monitoring Add-On
  hosts: all
  user: pi
  become: yes

  handlers:
    - name: restart-nginx
      service:
        name: nginx
        state: restarted

  roles:
    - add-on
