# Check older versions
- name: Create .monitor directory
  file:
    path: /home/pi/.monitor
    state: directory
    owner: pi
    group: pi
    mode: 0755

- set_fact: update_version="False"

- name: check if older version installed
  stat:
    path: /etc/nginx/sites-enabled/monitor.conf
  register: monitorScript_s

- set_fact: old_monitor="{{monitorScript_s.stat.exists}}"

- name: check if version 1.0 installed
  stat:
    path: /var/www/html/assets/tools/version.txt
  register: version1_0_s

- set_fact: version1_0="{{version1_0_s.stat.exists}}"

- name: check if version 1.1 installed
  stat:
    path: /var/www/html/monitor/assets/tools/version.txt
  register: version1_1_s

- set_fact: version1_1="{{version1_1_s.stat.exists}}"

- name: check if version 2.0 installed
  stat:
    path: /var/www/html/monitor/assets/tools/key.php
  register: version2_0_s

- set_fact: version2_0="{{version2_0_s.stat.exists}}"

- set_fact: update_version="True"
  when: (old_monitor) and (version1_0 or version1_1)

- name: check if old version code available
  stat:
    path: /var/www/html/monitor/assets/tools/version.txt
  register: versionscode_s

- set_fact: versionscode="{{versionscode_s.stat.exists}}"

- name: Backup Database
  copy:
    src: /var/www/html/dbase.db
    dest: /home/pi/.monitor/dbase.db.bak
    owner: pi
    group: pi
  when: update_version and version1_0

- name: Backup Database
  copy:
    src: /var/www/html/monitor/dbase.db
    dest: /home/pi/.monitor/dbase.db.bak
    owner: pi
    group: pi
  when: update_version and version1_1 and not version2_0

- name: Backup Version Code
  copy:
    src: /var/www/html/monitor/assets/tools/version.txt
    dest: /home/pi/.monitor/version.txt
    owner: pi
    group: pi
  when: versionscode

# Update ose-monitoring
- name: Install packages
  apt:
    name: "{{ packages }}"
    state: latest
    update_cache: yes
  vars:
    packages:
    - nginx-light
    - php-fpm
    - php-sqlite3
    - php-curl
    - php-ssh2

- name: Looking for the php version
  shell: "php -v | head -n1 | grep -Po '(?<=PHP )([0-9]+.[0-9]+)'"
  register: php_output

- set_fact:
    MONITORING_PHP_VERSION: "{{ php_output.stdout }}"

- name: Copy monitoing.conf
  template:
    src: monitoring.j2
    dest: /etc/nginx/sites-enabled/monitoring.conf

- name: Remove nginx default config by standalone installation
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent
  when: SERVER_MODE == "listen 80 default_server;"

- name: Change permissons for monitoring.conf
  file:
    path: /etc/nginx/sites-enabled/monitoring.conf
    owner: root
    group: root
    mode: 0644
  notify: restart-nginx

- name: Update php.ini memory_limit
  replace:
    dest: "/etc/php/{{MONITORING_PHP_VERSION}}/fpm/php.ini"
    regexp: '^memory_limit.*$'
    replace: 'memory_limit = 1024M'
    backup: yes

- name: Update php.ini post_max_size
  replace:
    dest: "/etc/php/{{MONITORING_PHP_VERSION}}/fpm/php.ini"
    regexp: '^post_max_size.*$'
    replace: 'post_max_size = 512M'
    backup: yes

- name: Update php.ini upload_max_filesize
  replace:
    dest: "/etc/php/{{MONITORING_PHP_VERSION}}/fpm/php.ini"
    regexp: '^upload_max_filesize.*$'
    replace: 'upload_max_filesize = 128M'
    backup: yes

- name: Restart PHP-FPM
  command: /bin/true
  notify: restart-fpm

- name: Clone repository from github.com
  git:
    repo: "https://github.com/didiatworkz/screenly-ose-monitor.git"
    dest: /var/www/html/monitor
    version: "{{ MONITOR_BRANCH }}"
    force: yes

- name: Copy ose-monitoring Script
  copy:
    src: ose-monitoring
    dest: /usr/bin/ose-monitoring
    owner: root
    group: root
    mode: 0755

- name: Change monitor owner
  file:
    path: /var/www/html/monitor
    state: directory
    owner: www-data
    group: www-data
    recurse: yes

- name: Retore Database Backup
  copy:
    src: /home/pi/.monitor/dbase.db.bak
    dest: /var/www/html/monitor/dbase.db
    owner: www-data
    group: www-data
    mode: 0644
  when: update_version

- name: Set old version when necessary
  copy:
    src: backup_version.txt
    dest: /var/www/html/monitor/assets/tools/version.txt
    owner: www-data
    group: www-data
    mode: 0644
  when: (old_monitor) and (version1_0 or version1_1)

- name: Retore Version Code
  copy:
    src: /home/pi/.monitor/version.txt
    dest: /var/www/html/monitor/assets/tools/version.txt
    owner: www-data
    group: www-data
    mode: 0644
  when: versionscode

- name: Version update
  command: ose-monitoring --init
