# Check older versions
    
- set_fact: update_version="False"

- name: check if older version installed
  stat:
    path: /etc/nginx/sites-enabled/screenshot.conf
  register: oldVersion_s

- set_fact: old_version="{{oldVersion_s.stat.exists}}"

- set_fact: update_version="True"
  when: old_version

- name: Remove old screenshot script
  file:
    state: absent
    path: "{{ file_list }}"
  vars:
    file_list:
    - /home/pi/screenshot.sh
    - /home/pi/screenshot.log
    - /var/www/html/screen/
    - /home/pi/screenshot.sh
    - /etc/nginx/sites-enabled/screenshot.conf
  when: update_version
  
- name: Remove old packages
  apt:
    name: "{{ packages }}"
    state: absent
  vars:
    packages:
    - nginx
  when: update_version
  
- name  : remove crontab
    shell : sudo crontab -r
  when: update_version
  
# Install Add-ons
- name: Install packages
  apt:
    name: "{{ packages }}"
    state: latest
    update_cache: yes
  vars:
    packages:
    - nginx-light 
    - x11-apps 
    - imagemagick
    
- name: Copy extension.conf
  copy:
    src: extension.conf
    dest: /etc/nginx/sites-enabled/extension.conf
    owner: root 
    group: root
    mode: 0644
  notify:
    - restart-nginx
    
- name: Copy screenshot.sh
  copy:
    src: screenshot.sh
    dest: /usr/bin/screenshot.sh
    owner: pi 
    group: pi
    mode: 0755
    
- name: Crontab for screenshot.sh
  cron:
    name: "Crontab for screenshot.sh"
    special_time: reboot
    job: "sleep 20 && /usr/bin/screenshot.sh >> /var/log/screenshot.log 2>1"

- file:
    path: /var/www/html/extension
    state: directory
    owner: www-data
    group: www-data
    recurse: yes
    
- name: Copy index.html
  copy:
    src: index.html
    dest: /var/www/html/extension/index.html
    owner: www-data
    group: www-data
    mode: 0644

- name: Copy monitor.txt
  copy:
    src: monitor.txt
    dest: /var/www/html/extension/monitor.txt
    owner: www-data
    group: www-data
    mode: 0644

- name: Copy loading image
  copy:
    src: loading.png
    dest: /var/www/html/extension/loading.png
    owner: www-data
    group: www-data
    mode: 0644
    
- name: Run a screenshot.sh
  script: /usr/bin/screenshot.sh